cabal-version:       3.6

name:                ssg
version:             0.1.0.0
build-type:          Simple
license:             BSD-3-Clause
license-file:        LICENSE

executable hakyll-site
  default-language:  Haskell2010
  main-is:           Main.hs
  hs-source-dirs:    src
  other-modules:     Hakyll.Site.Configuration
                   , Hakyll.Site.CustomFields
                   , Hakyll.Site.Feed
                   , Hakyll.Site.Post
                   , Hakyll.Site.Rules
                   , Hakyll.Site.Sitemap
                   , Text.HTML.TagSoup.Compressor
  build-depends:     base >= 4.17 && < 5
                   , containers >= 0.6
                   , hakyll >= 4.16 && < 4.18
                   , filepath >= 1.0
                   , pandoc >= 3.1 && < 3.8
                   , slugger >= 0.1.0.2
                   , tagsoup >= 0.14
                   , text >= 1 && < 3
                   , time >= 1.9
  ghc-options:     -Wall
                   -Wcompat
                   -Widentities
                   -Wincomplete-record-updates
                   -Wincomplete-uni-patterns
                   -Wpartial-fields
                   -Wredundant-constraints
                   -O2
                   -threaded
                   -rtsopts
                   -with-rtsopts=-N
